name: Build .NET MAUI Windows App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-maui-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI workload
        run: dotnet workload install maui

      # Build for Windows
      - name: Build MAUI Windows App
        run: dotnet build --configuration Release -f:net8.0-windows
